name: DiscordWhitelister
version: 1.4.7
author: Joe Shimell
main: uk.co.angrybee.joe.DiscordWhitelister
description: Discord Whitelister.
commands:
  discordwhitelister:
    description: See info about this plugin
    usage: /<command>
    aliases: [dw]
  discordwhitelisterabout:
    description: See plugin version and Discord connection status
    usage: /<command>
    aliases: [dwabout]
  discordwhitelisterreload:
    description: Hot reload Discord client
    usage: /<command>
    aliases: [dwreload]